import HomeIntro from "./HomeDashPages/HomeIntro/HomeIntro";
import HomeSec1 from "./HomeDashPages/HomeSec1/HomeSec1";
import AboutIntro from "./AboutDashPages/AboutIntro/AboutIntro";
import AboutSec1 from "./AboutDashPages/AboutSec1/AboutSec1";
import AboutSecTwo from "./AboutDashPages/AboutSecTwo/AboutSecTwo";
import AboutSecThr from "./AboutDashPages/AboutSecThr/AboutSecThr";
import ConstructionIntro from "./ConstructionDashPages/ConstructionIntro/ConstructionIntro";
import Constructionsec1 from "./ConstructionDashPages/Constructionsec1/Constructionsec1";
import ConstructionsecTwo from "./ConstructionDashPages/ConstructionsecTwo/ConstructionsecTwo";
import InteriorIntro from "./InteriorDashPages/InteriorIntro/InteriorIntro";
import InteriorSec1 from "./InteriorDashPages/InteriorSec1/InteriorSec1";
import InteriorSecTwo from "./InteriorDashPages/InteriorSecTwo/InteriorSecTwo";
import InteriorSecThr from "./InteriorDashPages/InteriorSecThr/InteriorISecThr";
import InteriorSecFour from "./InteriorDashPages/InteriorSecFour/InteriorSecFour";
import InteriorForm from './InteriorDashPages/InteriorForm/InteriorForm'
import InteriorSingleForm from './InteriorDashPages/InteriorSingleForm/InteriorSingleForm'
import BrandsPage from "./HomeDashPages/BrandHome/BrandHome";
import ProjectIntro from './ProjectDashPage/ProjectIntro/ProjectIntro'
import DashProjectDetail from './ProjectDashPage/DashProjectDetail/DashProjectDetail'
import AddProject from "./ProjectDashPage/AddProject/AddProject";
import ProductIntro from "./ProductDashPage/ProductIntro/ProductIntro";
import UpdateProject from "./ProjectDashPage/UpdateProject/UpdateProject";
import AddProduct from "./ProductDashPage/AddProduct/AddProduct";
import DashProductDetail from './ProductDashPage/DashProductDetail/DashProductDetail'
import UpdateProduct from './ProductDashPage/UpdateProduct/UpdateProduct'
import ContactForm from "./ContactDashPages/ContactForm/ContactForm";
import ContactSingleForm from "./ContactDashPages/ContactSingleForm/ContactSingleForm";
import HomeSliderSec1 from "./HomeDashPages/HomeSliderSec1/HomeSliderSec1";
import AddSliderInHome from "./HomeDashPages/AddSliderInHome/AddSliderInHome";
import UpdateSlideInHome from "./HomeDashPages/UpdateSlideInHome/UpdateSlideInHome";
import FaqsIntro from "./FAQsDashPage/FaqsIntro/FaqsIntro";
import DashfaqDetail from "./FAQsDashPage/DashFaqsDetail/DashfaqDetail";
import Addfaq from "./FAQsDashPage/Addfaq/Addfaq";
import UpdateFaq from "./FAQsDashPage/UpdateFaq/UpdateFaq";
import NewsIntro from "./NewsDashPage/NewsIntro/NewsIntro";
import DashNewsDetail from "./NewsDashPage/DashNewsDetail/DashNewsDetail";
import AddNews from "./NewsDashPage/AddNews/AddNews";
import UpdateNews from "./NewsDashPage/UpdateNews/UpdateNews";
import ContactIntro from "./ContactDashPages/ContactIntro/ContactIntro";


export {HomeIntro , HomeSec1,AboutIntro , AboutSec1 , AboutSecTwo , AboutSecThr,ConstructionIntro,Constructionsec1,ConstructionsecTwo, InteriorIntro,InteriorSec1,InteriorSecTwo,InteriorSecThr,InteriorSecFour,InteriorForm,InteriorSingleForm,BrandsPage , ProjectIntro , DashProjectDetail , AddProject,UpdateProject,AddProduct,DashProductDetail,UpdateProduct,ContactForm,ContactSingleForm , HomeSliderSec1,AddSliderInHome,UpdateSlideInHome , ProductIntro  , FaqsIntro , DashfaqDetail,Addfaq,UpdateFaq,NewsIntro , DashNewsDetail,AddNews,UpdateNews,ContactIntro}